name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run linting and code quality checks
        run: npm run lint && npm run code-quality

      - name: Run security vulnerability scanning
        run: npm audit

      - name: Run tests
        run: npm test

      - name: Provide feedback on pull request
        uses: pullreminders/comment-on-pull-request@v1
        with:
          message: |
            ## Code Review Results
            - Linting and code quality checks: Pass
            - Security vulnerability scanning: Pass
            - Tests: Pass
      - name: Comment on pull request
        run: node comment-on-pull-request.js
