name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Generate release notes
        run: npm run generate-release-notes

      - name: Save release notes as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release-notes.md
