name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  maintenance:
    name: Perform Maintenance
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run maintenance script
        run: npm run maintenance

      - name: Generate report
        run: npm run generate-report

      - name: Archive logs
        run: |
          mkdir -p logs
          cp maintenance.log logs/maintenance-$(date +"%Y-%m-%d").log

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: maintenance-logs
          path: logs/

      - name: Notify completion
        run: echo "Maintenance tasks completed successfully."

  notifications:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: maintenance
    steps:
      - name: Send Slack message
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          mentions: '@channel'
          text: |
            Maintenance tasks completed successfully!
            You can find the logs [here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
